services:
  api:
    image: "node:${NODE_VERSION}"
    command: "npm run start:dev"
    user: root
    working_dir: /home/node/nest
    environment:
      - PORT=${NESTJS_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS_ROOT=${DB_PASS_ROOT}
    ports:
      - "${NESTJS_PORT}:${NESTJS_PORT}"
    volumes:
      - .:/home/node/nest
    depends_on:
      - db 

  db:
    image: "mongo:${DB_VERSION}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS_ROOT}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:${DB_PORT}"

volumes:
  mongo_data:

